/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisakhapatnamRouteImport } from './routes/visakhapatnam'
import { Route as VijayawadaRouteImport } from './routes/vijayawada'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RajahmundryRouteImport } from './routes/rajahmundry'
import { Route as KakinadaRouteImport } from './routes/kakinada'
import { Route as HyderabadRouteImport } from './routes/hyderabad'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ApiSignCloudinaryRouteImport } from './routes/api.sign-cloudinary'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminCityPagesRouteImport } from './routes/admin.city-pages'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminSettingsTrustRouteImport } from './routes/admin.settings.trust'
import { Route as AdminSettingsSocialRouteImport } from './routes/admin.settings.social'
import { Route as AdminSettingsSeoRouteImport } from './routes/admin.settings.seo'
import { Route as AdminSettingsPopupRouteImport } from './routes/admin.settings.popup'
import { Route as AdminSettingsHomeRouteImport } from './routes/admin.settings.home'
import { Route as AdminSettingsHeroRouteImport } from './routes/admin.settings.hero'
import { Route as AdminSettingsFooterRouteImport } from './routes/admin.settings.footer'
import { Route as AdminSettingsCtaRouteImport } from './routes/admin.settings.cta'
import { Route as AdminSettingsContactRouteImport } from './routes/admin.settings.contact'
import { Route as AdminSettingsAnalyticsRouteImport } from './routes/admin.settings.analytics'
import { Route as AdminSettingsAboutRouteImport } from './routes/admin.settings.about'

const VisakhapatnamRoute = VisakhapatnamRouteImport.update({
  id: '/visakhapatnam',
  path: '/visakhapatnam',
  getParentRoute: () => rootRouteImport,
} as any)
const VijayawadaRoute = VijayawadaRouteImport.update({
  id: '/vijayawada',
  path: '/vijayawada',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RajahmundryRoute = RajahmundryRouteImport.update({
  id: '/rajahmundry',
  path: '/rajahmundry',
  getParentRoute: () => rootRouteImport,
} as any)
const KakinadaRoute = KakinadaRouteImport.update({
  id: '/kakinada',
  path: '/kakinada',
  getParentRoute: () => rootRouteImport,
} as any)
const HyderabadRoute = HyderabadRouteImport.update({
  id: '/hyderabad',
  path: '/hyderabad',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignCloudinaryRoute = ApiSignCloudinaryRouteImport.update({
  id: '/api/sign-cloudinary',
  path: '/api/sign-cloudinary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCityPagesRoute = AdminCityPagesRouteImport.update({
  id: '/admin/city-pages',
  path: '/admin/city-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsTrustRoute = AdminSettingsTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsSocialRoute = AdminSettingsSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsSeoRoute = AdminSettingsSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPopupRoute = AdminSettingsPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsHomeRoute = AdminSettingsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsHeroRoute = AdminSettingsHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsFooterRoute = AdminSettingsFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCtaRoute = AdminSettingsCtaRouteImport.update({
  id: '/cta',
  path: '/cta',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsContactRoute = AdminSettingsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAnalyticsRoute = AdminSettingsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAboutRoute = AdminSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/gallery': typeof GalleryRoute
  '/hyderabad': typeof HyderabadRoute
  '/kakinada': typeof KakinadaRoute
  '/rajahmundry': typeof RajahmundryRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/vijayawada': typeof VijayawadaRoute
  '/visakhapatnam': typeof VisakhapatnamRoute
  '/admin/city-pages': typeof AdminCityPagesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/sign-cloudinary': typeof ApiSignCloudinaryRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/analytics': typeof AdminSettingsAnalyticsRoute
  '/admin/settings/contact': typeof AdminSettingsContactRoute
  '/admin/settings/cta': typeof AdminSettingsCtaRoute
  '/admin/settings/footer': typeof AdminSettingsFooterRoute
  '/admin/settings/hero': typeof AdminSettingsHeroRoute
  '/admin/settings/home': typeof AdminSettingsHomeRoute
  '/admin/settings/popup': typeof AdminSettingsPopupRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/social': typeof AdminSettingsSocialRoute
  '/admin/settings/trust': typeof AdminSettingsTrustRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/gallery': typeof GalleryRoute
  '/hyderabad': typeof HyderabadRoute
  '/kakinada': typeof KakinadaRoute
  '/rajahmundry': typeof RajahmundryRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/vijayawada': typeof VijayawadaRoute
  '/visakhapatnam': typeof VisakhapatnamRoute
  '/admin/city-pages': typeof AdminCityPagesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/sign-cloudinary': typeof ApiSignCloudinaryRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/analytics': typeof AdminSettingsAnalyticsRoute
  '/admin/settings/contact': typeof AdminSettingsContactRoute
  '/admin/settings/cta': typeof AdminSettingsCtaRoute
  '/admin/settings/footer': typeof AdminSettingsFooterRoute
  '/admin/settings/hero': typeof AdminSettingsHeroRoute
  '/admin/settings/home': typeof AdminSettingsHomeRoute
  '/admin/settings/popup': typeof AdminSettingsPopupRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/social': typeof AdminSettingsSocialRoute
  '/admin/settings/trust': typeof AdminSettingsTrustRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enquiry': typeof EnquiryRoute
  '/gallery': typeof GalleryRoute
  '/hyderabad': typeof HyderabadRoute
  '/kakinada': typeof KakinadaRoute
  '/rajahmundry': typeof RajahmundryRoute
  '/services': typeof ServicesRouteWithChildren
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/vijayawada': typeof VijayawadaRoute
  '/visakhapatnam': typeof VisakhapatnamRoute
  '/admin/city-pages': typeof AdminCityPagesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/sign-cloudinary': typeof ApiSignCloudinaryRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/analytics': typeof AdminSettingsAnalyticsRoute
  '/admin/settings/contact': typeof AdminSettingsContactRoute
  '/admin/settings/cta': typeof AdminSettingsCtaRoute
  '/admin/settings/footer': typeof AdminSettingsFooterRoute
  '/admin/settings/hero': typeof AdminSettingsHeroRoute
  '/admin/settings/home': typeof AdminSettingsHomeRoute
  '/admin/settings/popup': typeof AdminSettingsPopupRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/social': typeof AdminSettingsSocialRoute
  '/admin/settings/trust': typeof AdminSettingsTrustRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/enquiry'
    | '/gallery'
    | '/hyderabad'
    | '/kakinada'
    | '/rajahmundry'
    | '/services'
    | '/signin'
    | '/sitemap.xml'
    | '/videos'
    | '/vijayawada'
    | '/visakhapatnam'
    | '/admin/city-pages'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/videos'
    | '/api/sign-cloudinary'
    | '/robots/txt'
    | '/services/$slug'
    | '/admin/'
    | '/admin/settings/about'
    | '/admin/settings/analytics'
    | '/admin/settings/contact'
    | '/admin/settings/cta'
    | '/admin/settings/footer'
    | '/admin/settings/hero'
    | '/admin/settings/home'
    | '/admin/settings/popup'
    | '/admin/settings/seo'
    | '/admin/settings/social'
    | '/admin/settings/trust'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/enquiry'
    | '/gallery'
    | '/hyderabad'
    | '/kakinada'
    | '/rajahmundry'
    | '/services'
    | '/signin'
    | '/sitemap.xml'
    | '/videos'
    | '/vijayawada'
    | '/visakhapatnam'
    | '/admin/city-pages'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/videos'
    | '/api/sign-cloudinary'
    | '/robots/txt'
    | '/services/$slug'
    | '/admin'
    | '/admin/settings/about'
    | '/admin/settings/analytics'
    | '/admin/settings/contact'
    | '/admin/settings/cta'
    | '/admin/settings/footer'
    | '/admin/settings/hero'
    | '/admin/settings/home'
    | '/admin/settings/popup'
    | '/admin/settings/seo'
    | '/admin/settings/social'
    | '/admin/settings/trust'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/enquiry'
    | '/gallery'
    | '/hyderabad'
    | '/kakinada'
    | '/rajahmundry'
    | '/services'
    | '/signin'
    | '/sitemap.xml'
    | '/videos'
    | '/vijayawada'
    | '/visakhapatnam'
    | '/admin/city-pages'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/videos'
    | '/api/sign-cloudinary'
    | '/robots/txt'
    | '/services/$slug'
    | '/admin/'
    | '/admin/settings/about'
    | '/admin/settings/analytics'
    | '/admin/settings/contact'
    | '/admin/settings/cta'
    | '/admin/settings/footer'
    | '/admin/settings/hero'
    | '/admin/settings/home'
    | '/admin/settings/popup'
    | '/admin/settings/seo'
    | '/admin/settings/social'
    | '/admin/settings/trust'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EnquiryRoute: typeof EnquiryRoute
  GalleryRoute: typeof GalleryRoute
  HyderabadRoute: typeof HyderabadRoute
  KakinadaRoute: typeof KakinadaRoute
  RajahmundryRoute: typeof RajahmundryRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideosRoute: typeof VideosRoute
  VijayawadaRoute: typeof VijayawadaRoute
  VisakhapatnamRoute: typeof VisakhapatnamRoute
  AdminCityPagesRoute: typeof AdminCityPagesRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  ApiSignCloudinaryRoute: typeof ApiSignCloudinaryRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visakhapatnam': {
      id: '/visakhapatnam'
      path: '/visakhapatnam'
      fullPath: '/visakhapatnam'
      preLoaderRoute: typeof VisakhapatnamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vijayawada': {
      id: '/vijayawada'
      path: '/vijayawada'
      fullPath: '/vijayawada'
      preLoaderRoute: typeof VijayawadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rajahmundry': {
      id: '/rajahmundry'
      path: '/rajahmundry'
      fullPath: '/rajahmundry'
      preLoaderRoute: typeof RajahmundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kakinada': {
      id: '/kakinada'
      path: '/kakinada'
      fullPath: '/kakinada'
      preLoaderRoute: typeof KakinadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyderabad': {
      id: '/hyderabad'
      path: '/hyderabad'
      fullPath: '/hyderabad'
      preLoaderRoute: typeof HyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sign-cloudinary': {
      id: '/api/sign-cloudinary'
      path: '/api/sign-cloudinary'
      fullPath: '/api/sign-cloudinary'
      preLoaderRoute: typeof ApiSignCloudinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/city-pages': {
      id: '/admin/city-pages'
      path: '/admin/city-pages'
      fullPath: '/admin/city-pages'
      preLoaderRoute: typeof AdminCityPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/trust': {
      id: '/admin/settings/trust'
      path: '/trust'
      fullPath: '/admin/settings/trust'
      preLoaderRoute: typeof AdminSettingsTrustRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/social': {
      id: '/admin/settings/social'
      path: '/social'
      fullPath: '/admin/settings/social'
      preLoaderRoute: typeof AdminSettingsSocialRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/seo': {
      id: '/admin/settings/seo'
      path: '/seo'
      fullPath: '/admin/settings/seo'
      preLoaderRoute: typeof AdminSettingsSeoRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/popup': {
      id: '/admin/settings/popup'
      path: '/popup'
      fullPath: '/admin/settings/popup'
      preLoaderRoute: typeof AdminSettingsPopupRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/home': {
      id: '/admin/settings/home'
      path: '/home'
      fullPath: '/admin/settings/home'
      preLoaderRoute: typeof AdminSettingsHomeRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/hero': {
      id: '/admin/settings/hero'
      path: '/hero'
      fullPath: '/admin/settings/hero'
      preLoaderRoute: typeof AdminSettingsHeroRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/footer': {
      id: '/admin/settings/footer'
      path: '/footer'
      fullPath: '/admin/settings/footer'
      preLoaderRoute: typeof AdminSettingsFooterRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/cta': {
      id: '/admin/settings/cta'
      path: '/cta'
      fullPath: '/admin/settings/cta'
      preLoaderRoute: typeof AdminSettingsCtaRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/contact': {
      id: '/admin/settings/contact'
      path: '/contact'
      fullPath: '/admin/settings/contact'
      preLoaderRoute: typeof AdminSettingsContactRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/analytics': {
      id: '/admin/settings/analytics'
      path: '/analytics'
      fullPath: '/admin/settings/analytics'
      preLoaderRoute: typeof AdminSettingsAnalyticsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/about': {
      id: '/admin/settings/about'
      path: '/about'
      fullPath: '/admin/settings/about'
      preLoaderRoute: typeof AdminSettingsAboutRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsAboutRoute: typeof AdminSettingsAboutRoute
  AdminSettingsAnalyticsRoute: typeof AdminSettingsAnalyticsRoute
  AdminSettingsContactRoute: typeof AdminSettingsContactRoute
  AdminSettingsCtaRoute: typeof AdminSettingsCtaRoute
  AdminSettingsFooterRoute: typeof AdminSettingsFooterRoute
  AdminSettingsHeroRoute: typeof AdminSettingsHeroRoute
  AdminSettingsHomeRoute: typeof AdminSettingsHomeRoute
  AdminSettingsPopupRoute: typeof AdminSettingsPopupRoute
  AdminSettingsSeoRoute: typeof AdminSettingsSeoRoute
  AdminSettingsSocialRoute: typeof AdminSettingsSocialRoute
  AdminSettingsTrustRoute: typeof AdminSettingsTrustRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsAboutRoute: AdminSettingsAboutRoute,
  AdminSettingsAnalyticsRoute: AdminSettingsAnalyticsRoute,
  AdminSettingsContactRoute: AdminSettingsContactRoute,
  AdminSettingsCtaRoute: AdminSettingsCtaRoute,
  AdminSettingsFooterRoute: AdminSettingsFooterRoute,
  AdminSettingsHeroRoute: AdminSettingsHeroRoute,
  AdminSettingsHomeRoute: AdminSettingsHomeRoute,
  AdminSettingsPopupRoute: AdminSettingsPopupRoute,
  AdminSettingsSeoRoute: AdminSettingsSeoRoute,
  AdminSettingsSocialRoute: AdminSettingsSocialRoute,
  AdminSettingsTrustRoute: AdminSettingsTrustRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EnquiryRoute: EnquiryRoute,
  GalleryRoute: GalleryRoute,
  HyderabadRoute: HyderabadRoute,
  KakinadaRoute: KakinadaRoute,
  RajahmundryRoute: RajahmundryRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideosRoute: VideosRoute,
  VijayawadaRoute: VijayawadaRoute,
  VisakhapatnamRoute: VisakhapatnamRoute,
  AdminCityPagesRoute: AdminCityPagesRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminVideosRoute: AdminVideosRoute,
  ApiSignCloudinaryRoute: ApiSignCloudinaryRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
